Resources:
  CourseRating:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:provider.stage}-courses-rating
      AttributeDefinitions:
        - AttributeName: "course_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "course_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
