package app.uvsy.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import app.uvsy.model.converters.TagConverter;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
@DynamoDBTable(tableName = "student-courses-rating")
public class StudentCourseRating {

    @DynamoDBHashKey(attributeName = "user_id")
    private String userId;

    @DynamoDBRangeKey(attributeName = "course_id")
    private String courseId;

    @DynamoDBAttribute(attributeName = "overall")
    private int overall;

    @DynamoDBAttribute(attributeName = "difficulty")
    private int difficulty;

    @DynamoDBAttribute(attributeName = "would_take_again")
    private boolean wouldTakeAgain;

    @DynamoDBTypeConverted(converter = TagConverter.class)
    @DynamoDBAttribute(attributeName = "tags")
    private List<Tag> tags;

    @DynamoDBAttribute(attributeName = "updated_at")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updatedAt;

    @DynamoDBAttribute(attributeName = "created_at")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

}
