package app.uvsy.model;

public enum Tag {
    HARD_PRACTICAL,
    HARD_THEORETICAL,
    MANDATORY_CLASS,
    HARD_TO_UNDERSTAND,
    PROMOTIONABLE,
    DONT_GO_THERE,
    MIND_BLOWING,
    BE_READY_FOR_PW,
    TO_MUCH_EXTRA_TIME,
    SUMMARIES_AVAILABLE
}
